# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot = {
    initrd.availableKernelModules = [ ];
    initrd.kernelModules = [ ];
    kernelModules = [ "nvme0n1" ];
    extraModulePackages = [ ];

    tmpOnTmpfs = true;
  };

  # TODO: get this shit
  fileSystems."/" =
    { device = "/dev/mmcblk0p2";
      fsType = "devtmpfs";
    };

  swapDevices =
    [ { device = "/swapfile"; size = 1024; } ];
}
