# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot = {
    initrd.availableKernelModules = [ ];
    initrd.kernelModules = [ "nvme" ];
    kernelModules = [ ];
    extraModulePackages = [ ];

    kernelPackages = pkgs.linuxPackages_latest;
    tmpOnTmpfs = true;
  };

  fileSystems."/" =
    { device = "/dev/sda1";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3E21-E7C9";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/swapfile"; size = 1024; } ];
}
